CREATE TABLE `meta_launch_drafts` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`channel` text DEFAULT 'meta',
	`account_id` text NOT NULL,
	`center` text DEFAULT 'network',
	`objective` text DEFAULT 'OUTCOME_LEADS',
	`campaign_name` text NOT NULL,
	`adset_name` text,
	`ad_name` text,
	`status` text DEFAULT 'draft',
	`priority` text DEFAULT 'medium',
	`audience_summary` text,
	`geo_targets` text,
	`placements` text,
	`budget_type` text DEFAULT 'daily',
	`budget_inr` real DEFAULT 0,
	`budget_notes` text,
	`utm_campaign` text,
	`landing_url` text,
	`content_angle` text,
	`hook` text,
	`primary_text` text,
	`headline` text,
	`description` text,
	`cta` text,
	`creative_format` text,
	`creative_brief` text,
	`content_keywords` text,
	`content_owner_name` text,
	`performance_owner_name` text,
	`requested_by_email` text,
	`requested_by_name` text,
	`approval_requested_at` text,
	`approved_by_email` text,
	`approved_by_name` text,
	`approved_at` text,
	`approval_notes` text,
	`ads_manager_link` text,
	`launch_checklist` text,
	`launch_notes` text,
	`launched_at` text,
	`created_at` text DEFAULT CURRENT_TIMESTAMP,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP
);
